package ift605tp2.client;

import ift605tp2.client.parsers.BasicParser;
import ift605tp2.client.parsers.ConstantParser;
import ift605tp2.client.parsers.IEquationParser;
import ift605tp2.client.parsers.MultiplicativeParser;
import ift605tp2.client.parsers.SummativeParser;
import udes.ds.agent.AbstractEquation;
import udes.ds.agent.Equation;

/**
 *
 * @author Michaël
 */
public class DerivationForm extends javax.swing.JFrame {

    private final ClientManager m_manager;
    private IEquationParser m_selectedParser;

    /**
     * Creates new form DerivationForm
     */
    public DerivationForm() {
        m_manager = new ClientManager();
        m_selectedParser = new ConstantParser();
        initComponents();
    }
    
    public void AppendOutput(String message){
        txtOutput.append(message + "\r\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equationTypeGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtHostname = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlEquation = new javax.swing.JPanel();
        btnDerivate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEquation = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        optConstant = new javax.swing.JRadioButton();
        optBasic = new javax.swing.JRadioButton();
        optMult = new javax.swing.JRadioButton();
        optSum = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setToolTipText("");
        jPanel1.setName("grpLogin"); // NOI18N

        jLabel1.setText("Hostname:");

        txtHostname.setText("localhost");
        txtHostname.setName("txtHostname"); // NOI18N

        btnLogin.setText("Login");
        btnLogin.setName("btnLogin"); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLogin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHostname)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHostname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Authenticating to server");

        pnlEquation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnDerivate.setText("Derivate");
        btnDerivate.setName("btnDerivate"); // NOI18N
        btnDerivate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDerivateMouseClicked(evt);
            }
        });

        txtEquation.setColumns(20);
        txtEquation.setRows(5);
        txtEquation.setName("txtEquation"); // NOI18N
        jScrollPane1.setViewportView(txtEquation);

        jLabel5.setText("Equation:");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        equationTypeGroup.add(optConstant);
        optConstant.setSelected(true);
        optConstant.setText("Constant");
        optConstant.setToolTipText("Only write the constant value (Ex: 2)");
        optConstant.setName("optConstant"); // NOI18N
        optConstant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationTypeSelected(evt);
            }
        });

        equationTypeGroup.add(optBasic);
        optBasic.setText("Basic Equation");
        optBasic.setToolTipText("Write both coefficient & exponent separated by spaces (Ex. 2 3 => 2x^3)");
        optBasic.setActionCommand("Basic");
        optBasic.setName("optBasic"); // NOI18N
        optBasic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationTypeSelected(evt);
            }
        });

        equationTypeGroup.add(optMult);
        optMult.setText("Multiplicative Equation");
        optMult.setToolTipText("<html>Write each basic terms on different lines<br/> (Ex:<br/> 2 3 <br/> 4 5<br/>=> 2x^3 * 4x^5)</html>");
        optMult.setActionCommand("Multiplicative");
        optMult.setName("optMult"); // NOI18N
        optMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationTypeSelected(evt);
            }
        });

        equationTypeGroup.add(optSum);
        optSum.setText("Summative Equation");
        optSum.setToolTipText("<html>Write each basic terms on different lines<br/> (Ex:<br/> 2 3 <br/> 4 5<br/>=> 2x^3 + 4x^5)</html>");
        optSum.setActionCommand("Summative");
        optSum.setName("optSum"); // NOI18N
        optSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equationTypeSelected(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optConstant)
                    .addComponent(optBasic)
                    .addComponent(optMult)
                    .addComponent(optSum))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optConstant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optBasic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optMult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optSum)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel6.setText("Equation type:");

        javax.swing.GroupLayout pnlEquationLayout = new javax.swing.GroupLayout(pnlEquation);
        pnlEquation.setLayout(pnlEquationLayout);
        pnlEquationLayout.setHorizontalGroup(
            pnlEquationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEquationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEquationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlEquationLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(pnlEquationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(pnlEquationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnDerivate, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlEquationLayout.setVerticalGroup(
            pnlEquationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEquationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEquationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlEquationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDerivate)
                .addContainerGap())
        );

        jLabel4.setText("Equation entry");

        txtOutput.setColumns(20);
        txtOutput.setRows(5);
        txtOutput.setName("txtOutput"); // NOI18N
        jScrollPane2.setViewportView(txtOutput);

        jLabel7.setText("Output box:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlEquation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlEquation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equationTypeSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equationTypeSelected
        String selectedType = evt.getActionCommand();
        if (selectedType.equalsIgnoreCase(EquationType.Constant.name())) {
            m_selectedParser = new ConstantParser();
        }
        if (selectedType.equalsIgnoreCase(EquationType.Basic.name())) {
            m_selectedParser = new BasicParser();
        }
        if (selectedType.equalsIgnoreCase(EquationType.Multiplicative.name())) {
            m_selectedParser = new MultiplicativeParser();
        }
        if (selectedType.equalsIgnoreCase(EquationType.Summative.name())) {
            m_selectedParser = new SummativeParser();
        }
    }//GEN-LAST:event_equationTypeSelected

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        m_manager.Connect(txtHostname.getText());
        if (m_manager.IsConnected()) {
            AppendOutput("Now connected on " + txtHostname.getText());
        } else {
            AppendOutput("Connection failed. See logger for details on the exception.");
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnDerivateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDerivateMouseClicked
        // TODO add your handling code here:
        AbstractEquation parsedEquation = (AbstractEquation) m_selectedParser.ParseEquation(txtEquation.getText());
        AbstractEquation eq = m_manager.Derivate((Equation)parsedEquation);
        if (eq == null) {
            AppendOutput("Error while derivating equation.");
        } else {
            AppendOutput("Derivation of " + parsedEquation.getUserReadableString() + " = " + eq.getUserReadableString());
        }
    }//GEN-LAST:event_btnDerivateMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DerivationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DerivationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DerivationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DerivationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DerivationForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDerivate;
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup equationTypeGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton optBasic;
    private javax.swing.JRadioButton optConstant;
    private javax.swing.JRadioButton optMult;
    private javax.swing.JRadioButton optSum;
    private javax.swing.JPanel pnlEquation;
    private javax.swing.JTextArea txtEquation;
    private javax.swing.JTextField txtHostname;
    private javax.swing.JTextArea txtOutput;
    // End of variables declaration//GEN-END:variables

}
